### ISSUE TITLE
Staging buffer sizes should be per-queue

### ISSUE THREAD

**Issue by sherief** [microsoft/DirectStorage#13]
A per-process one-size-fits-all might work for games on Xbox, but working on a high-end PC content creation tool this is just not working for me. 4K uncompressed textures (development build, content creation, background async compression while live reloading etc) need a large staging buffer size, while during sculpting geometry I can live with much smaller sizes and I want the VA / BAR address space.

**Comment by damyanp** [comment]
In DirectStorage, the staging buffer is shared between all the queues, and so in the current design it doesn't really make sense to think about different sized staging buffers for different queues.
