### ISSUE TITLE
GpuDecompressionBenchmark compiling issue

### ISSUE THREAD

**Issue by fdoreng** [microsoft/DirectStorage#18]
Trying to compile GpuDecompressionBenchmark to X64 but fails.
Looks like its looking for ARM64 and fail when compiling to X64 on a X64 system.

![Screenshot 2022-11-22 125859](https://user-images.githubusercontent.com/61248806/203420299-4063b04a-708a-42de-9e5d-eced12226fa6.png)
![Screenshot 2022-11-22 125933](https://user-images.githubusercontent.com/61248806/203420308-ff5b4982-b0b1-4bb5-93ba-b9f51363754c.png)

Any idea why?

**Comment by damyanp** [comment]
Apologies for the delay here, it looks like I missed this.  @fdoreng, did you manage to resolve this?  Can you double check that the target for all the projects is set to x64 please?

**Comment by fdoreng** [comment]
Yes I had someone recompile it on an ARM64 to X64 and that worked.
Just could't recompile directly on a X64 system with the target sat to x64

**Comment by damyanp** [comment]
Ok, thanks.  I'm going to close this for now as we're not seeing this issue ourselves.  If you'd like to continue looking into it we'll need to start grabbing more detailed msbuild logs from your machine.
