### ISSUE TITLE
Publish Bulk Load Demo as compiled release for x64 and ARM (AvocadoMark)

### ISSUE THREAD

**Issue by tauheedul** [microsoft/DirectStorage#30]
Please can the Bulk Load Demo sample be released as a binary in Github for many of us who are not experienced with C++ and only want to run the application locally? (without the source code)

- We simply would like to download it as a binary and run the Avocado demo with default pre-sets as a basic benchmark.
- It would be useful if the results are automatically traced to a log file after each iteration.
- The BulkLoadDemo is often shared as screenshots by enthusiasts after Benchmarking a graphics card but it currently does not include the Device Name and Model in the header. This would be helpful while comparing two screenshots side by side.

![image](https://user-images.githubusercontent.com/9335220/227920166-51bf2179-779e-45a4-a905-2688e97a87f0.png)

As a .NET Developer with limited experience with C++ I was unable to compile the Sample solution in Visual Studio 2022 17.5 and 17.6 Preview 2.0.

Previously I was able to drop in the missing Avocado.marc file into the Release directory (from 3rd party) and then compile and the test application would work. Currently we have to browse the internet for an unofficial compiled version.

![image](https://user-images.githubusercontent.com/9335220/227919845-f71a366f-731e-4523-a8da-170d20bb1201.png)

**Comment by oscarbg** [comment]
+1

**Comment by ValZapod** [comment]
Here: https://forums.guru3d.com/threads/directstorage-1-1-benchmark.446299/

**Comment by damyanp** [comment]
Hi.  Just to let you know that we have no plans to release binaries of these samples.  The samples in this repository are educational aids intended to show developers how to use the DirectStorage API.

**Comment by tauheedul** [comment]
> Hi. Just to let you know that we have no plans to release binaries of these samples. The samples in this repository are educational aids intended to show developers how to use the DirectStorage API.

I understand. I would like to compile the solution locally, unfortunately the solution does not compile in it's default configuration when using Visual Studio 2022. I see the error MSB3073. 

I downloaded the sample repo, upgraded the solution to Visual Studio 2022 for Windows 11 but the demo does not run.

The command "C:\Users\tauhe\Documents\Visual Studio 2022\DirectStorage-main\DirectStorage-main\Samples\BulkLoadDemo\PropertySheets\..\Build\x64\Release\Output\BulkLoadDemo\../miniarchive/miniarchive.exe SampleModel/Avocado.gltf C:\Users\tauhe\Documents\Visual Studio 2022\DirectStorage- BulkLoadDemo main\DirectStorage-main\DirectStorage-main\Samples\BulkLoadDemo\PropertySheets\..\Build\x64\Release\Output\BulkLoadDemo\Avocado.marc -gdeflate -bc" exited with code 9009.

Ideally the Demo sample should compile with no modification required for beginners.

**Comment by damyanp** [comment]
@tauheedul - see #32.

**Comment by tauheedul** [comment]
> @tauheedul - see #32.

Thank you, this fix worked and it compiles when the project has spaces in the file name path e.g. the Visual Studio 2022 directory.

![image](https://user-images.githubusercontent.com/9335220/235147335-6bbcf09d-73d6-42a6-a50e-04fc723e2c3e.png)
