### ISSUE TITLE
Documentation still requires an NDA

### ISSUE THREAD

**Issue by leeter** [microsoft/DirectStorage#6]
So while this is public and we can see the samples... the documentation still requires an NDA

https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/reference/system/dstorage/dstorage_members

Can we get a public version of this put under the proper DirectX category on docs.microsoft.com as this is now public?

**Comment by damyanp** [comment]
Please see https://github.com/microsoft/DirectStorage/blob/main/Docs/DeveloperGuidance.md

**Comment by leeter** [comment]
Unfortunately the linked documentation does not adequately cover the API itself only high level usage. That documentation is still locked behind an NDA. So right now Developer do not have access to how to properly use the API other than the samples.

**Comment by leeter** [comment]
Specifically the contents of https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/reference/system/dstorage/dstorage_members MUST be made public to properly use the API without abuse.

**Comment by damyanp** [comment]
Currently, please see dstorage.h for reference documentation for the Windows version of DirectStorage.

**Comment by leeter** [comment]
A header file is not documentation. It does not document expected return values or intricacies of use. I'll just recommend against use until this is properly documented.
